name: Python Pytest Github Action
description: 'Pytest Github Action running on python slim docker image'
inputs:
  package_name: 
    description: 'package name'
    required: true
  verbosity:
    description: 'whole report or just score'
    required: false
    default: score
outputs:
  pytest-report:
    description: 'Summary or just score from pytest'
branding:
  icon: box
  color: red
runs-on: ubuntu-latest
runs:
  using: 'docker'
  image: 'Dockerfile'
steps:
- uses: actions/checkout@master
- name: Python Pylint Github Action
  uses: benstear/biopypir-pytest-action@master
  with:
    args: pytest --help
